# Simple workflow for deploying static content to Github Pages
name: Deploy static content to Pages

on:
  # Runs os pushes targeting the default brance
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Download & Extract Playwright Report
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.YOUR_GITHUB_PAT }}
          repo: oearhp/api-automation-playwright
          workflow: playwright.yml
          name: playwright-report
          path: ./dist/report
          if_no_artifact_found: warn
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v5